### ISSUE TITLE
监听文件变化应该做成可配置的

### ISSUE THREAD

**Issue by AnnVoV** [NodeLab/qin#14]
因为总是监听文件会卡！用户体验不太好~别的地方都很好~很喜欢

**Comment by ArvoGuo** [comment]
@AnnVoV  
尊敬的用户您好，我们会满足您任何需求。
您的需求功能已经添加，只需在启动时加入参数 -e 或者 --easy  就不会监听文件变化。
敬请关注新版本，或者我们会请首席推广为您安装bate版。
