### ISSUE TITLE
新添加的-e 参数无效，ftl 都没法解析了，投诉！

### ISSUE THREAD

**Issue by AnnVoV** [NodeLab/qin#19]
新添加的-e 参数无效，ftl 都没法解析了，投诉！ 紧急事件哔哔哔哔哔！btw 推广大使很生气

**Comment by ArvoGuo** [comment]
@AnnVoV 万分抱歉 － － ，请稍候 紧急修复中。

**Comment by elrrrrrrr** [comment]
reload.js 在easy mode下，将请求直接交由下个router，会由static返回。
现在在reload中判断有没有 fmcontent 返回。

easy mode下 socket和watcher应该不加载。
