### ISSUE TITLE
bug  qin -i 

### ISSUE THREAD

**Issue by ArvoGuo** [NodeLab/qin#23]
✗ qin -i  
 http://10.97.192.49:8000/ 
{ [Error: ENOENT, lstat '/Users/Arvo/github/qin/template/config.json']
  errno: 34,
  code: 'ENOENT',
  path: '/Users/Arvo/github/qin/template/config.json' }

貌似被我干掉了

**Comment by elrrrrrrr** [comment]
恩的 忘记说了 :smile:

**Comment by elrrrrrrr** [comment]
fixed by @ArvoGuo
